In [7]:
# Load the "autoreload" extension
%load_ext autoreload

# always reload modules marked with "%aimport"
%autoreload 1

import os
import sys

from dotenv import load_dotenv, find_dotenv
import numpy as np
import pandas as pd

# add the 'src' directory as one where we can import modules
src_dir = os.path.join(os.getcwd(), os.pardir, 'src')
sys.path.append(src_dir)

%aimport data.preprocessing
from data.preprocessing import Preprocessor
%aimport data.download
from data.download import DatasetDownloader

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [23]:
data_dir = os.path.join(os.path.abspath(DatasetDownloader.get_data_dir()))
file_path = os.path.join(data_dir, "preprocessed","preprocessed_data_total.csv")
dfs = pd.read_csv(file_path, sep=';', index_col=False)

In [33]:
dfs.head()

,snippet_0,snippet_1,snippet_2,snippet_3,snippet_4,snippet_5,snippet_6,snippet_7,snippet_8,snippet_9,...,snippet_595,snippet_596,snippet_597,snippet_598,snippet_599,mode,notes,scripted,token,trip_id
0,9.670845,9.680774,9.667165,9.677708,9.672548,9.677967,9.668940,9.671821,9.681724,9.682986,...,9.677611,9.680940,9.674599,9.678326,9.679511,TRAM,scripted,1,355007075245007,0
1,9.668308,9.678738,9.675576,9.674167,9.690532,9.692198,9.681169,9.681573,9.687021,9.692332,...,9.695430,9.670247,9.677863,9.656445,9.696049,TRAM,scripted,1,355007075245007,0
2,9.678036,9.662953,9.715737,9.661738,9.671797,9.699416,9.689759,9.673749,9.694505,9.660014,...,9.663122,9.902346,9.463029,9.763390,9.632184,TRAM,scripted,1,355007075245007,0
3,9.604166,9.790406,9.595141,9.680603,9.745095,9.711922,9.606472,9.608852,9.669471,9.705075,...,9.711997,9.698935,9.691110,9.687026,9.699683,TRAM,scripted,1,355007075245007,0
4,9.694020,9.707281,9.700659,9.701931,9.701505,9.685484,9.705397,9.708873,9.693638,9.694002,...,9.669317,9.561652,9.613489,9.745893,9.603682,TRAM,scripted,1,355007075245007,0

In [65]:
file_path = os.path.join(data_dir, "preprocessed","preprocessed_data.dat")
dfs_raw = Preprocessor.restore_preprocessed_data_from_disk(file_path)

In [72]:
sensors_data = dfs_raw['355007075245007'][1]

In [71]:
set(sensors_data)

{'acceleration', 'gyroscope', 'linacc', 'magnetic', 'rotation'}

In [75]:
sensors_data['location']

,gpstime,time,provider,longitude,latitude,altitude,speed,bearing,accuracy
58,2017-12-13 15:06:21.000,2017-12-13 15:06:22.078,1,16.357055,48.219098,231.317001,0.000000,0.000000,24.000000
59,2017-12-13 15:06:21.000,2017-12-13 15:06:22.082,1,16.357055,48.219098,231.317001,0.000000,0.000000,24.000000
60,2017-12-13 15:06:22.000,2017-12-13 15:06:22.993,1,16.357055,48.219098,229.840469,0.000000,0.000000,16.000000
61,2017-12-13 15:06:22.000,2017-12-13 15:06:22.994,1,16.357055,48.219098,229.840469,0.000000,0.000000,16.000000
62,2017-12-13 15:06:23.000,2017-12-13 15:06:24.005,1,16.356996,48.219078,229.222900,1.537444,0.000000,32.000000
63,2017-12-13 15:06:23.000,2017-12-13 15:06:24.007,1,16.356996,48.219078,229.222900,1.537444,0.000000,32.000000
64,2017-12-13 15:06:24.000,2017-12-13 15:06:24.983,1,16.356964,48.219074,228.900314,1.807215,0.000000,24.000000
65,2017-12-13 15:06:24.000,2017-12-13 15:06:24.984,1,16.356964,48.219074,228.900314,1.807215,0.000000,24.000000
66,2017-12-13 15:06:25.000,2017-12-13 15:06:26.022,1,16.356941,48.219066,228.903717,1.801942,0.000000,24.000000
67,2017-12-13 15:06:25.000,2017-12-13 15:06:26.024,1,16.356941,48.219066,228.903717,1.801942,0.000000,24.000000
68,2017-12-13 15:06:26.000,2017-12-13 15:06:26.977,1,16.356935,48.219051,228.902786,1.819519,0.000000,24.000000
69,2017-12-13 15:06:26.000,2017-12-13 15:06:26.979,1,16.356935,48.219051,228.902786,1.819519,0.000000,24.000000
70,2017-12-13 15:06:27.000,2017-12-13 15:06:28.044,1,16.356925,48.219044,229.003769,1.846439,0.000000,12.000000
71,2017-12-13 15:06:27.000,2017-12-13 15:06:28.046,1,16.356925,48.219044,229.003769,1.846439,0.000000,12.000000
72,2017-12-13 15:06:28.000,2017-12-13 15:06:29.046,1,16.356902,48.219053,228.983688,1.836749,0.000000,12.000000
73,2017-12-13 15:06:28.000,2017-12-13 15:06:29.056,1,16.356902,48.219053,228.983688,1.836749,0.000000,12.000000
74,2017-12-13 15:06:24.402,2017-12-13 15:06:29.975,0,16.356926,48.219072,0.000000,0.000000,0.000000,21.016001
75,2017-12-13 15:06:24.402,2017-12-13 15:06:29.977,0,16.356926,48.219072,0.000000,0.000000,0.000000,21.016001
76,2017-12-13 15:06:29.000,2017-12-13 15:06:29.994,1,16.356887,48.219058,229.038574,1.797953,0.000000,24.000000
77,2017-12-13 15:06:29.000,2017-12-13 15:06:29.995,1,16.356887,48.219058,229.038574,1.797953,0.000000,24.000000
78,2017-12-13 15:06:30.000,2017-12-13 15:06:31.007,1,16.356875,48.219057,229.108414,1.737401,0.000000,12.000000
79,2017-12-13 15:06:30.000,2017-12-13 15:06:31.010,1,16.356875,48.219057,229.108414,1.737401,0.000000,12.000000
80,2017-12-13 15:06:31.000,2017-12-13 15:06:31.995,1,16.356866,48.219050,229.040451,1.696834,0.000000,16.000000
81,2017-12-13 15:06:31.000,2017-12-13 15:06:31.996,1,16.356866,48.219050,229.040451,1.696834,0.000000,16.000000
82,2017-12-13 15:06:32.000,2017-12-13 15:06:33.026,1,16.356855,48.219045,229.031281,1.667984,0.000000,16.000000
83,2017-12-13 15:06:32.000,2017-12-13 15:06:33.029,1,16.356855,48.219045,229.031281,1.667984,0.000000,16.000000
84,2017-12-13 15:06:33.000,2017-12-13 15:06:34.034,1,16.356840,48.219041,229.028091,1.648050,0.000000,16.000000
85,2017-12-13 15:06:33.000,2017-12-13 15:06:34.036,1,16.356840,48.219041,229.028091,1.648050,0.000000,16.000000
86,2017-12-13 15:06:34.000,2017-12-13 15:06:35.030,1,16.356836,48.219025,229.057068,1.653867,0.000000,32.000000
87,2017-12-13 15:06:34.000,2017-12-13 15:06:35.031,1,16.356836,48.219025,229.057068,1.653867,0.000000,32.000000
...,...,...,...,...,...,...,...,...,...
1238,2017-12-13 15:16:02.999,2017-12-13 15:16:03.982,1,16.352736,48.215759,222.871078,0.000000,153.022522,12.000000
1239,2017-12-13 15:16:02.999,2017-12-13 15:16:03.987,1,16.352736,48.215759,222.871078,0.000000,153.022522,12.000000
1240,2017-12-13 15:16:03.999,2017-12-13 15:16:05.021,1,16.352739,48.215725,222.973740,0.000000,174.278595,12.000000
1241,2017-12-13 15:16:03.999,2017-12-13 15:16:05.023,1,16.352739,48.215725,222.973740,0.000000,174.278595,12.000000
1242,2017-12-13 15:16:04.999,2017-12-13 15:16:06.016,1,16.352737,48.215704,223.137756,0.000000,177.350708,12.000000
1243,2017-12-13 15:16:04.999,2017-12-13 15:16:06.018,1,16.352737,48.215704,223.137756,0.000000,177.350708,12.000000
1244,2017-12-13 15:16:05.999,2017-12-13 15:16:07.041,1,16.352730,48.215695,223.122833,0.610135,205.788101,16.000000
1245,2017-12-13 15:16:05.999,2017-12-13 15:16:07.043,1,16.352730,48.215695,223.122833,0.610135,205.788101,16.000000
1246,2017-12-13 15:16:06.999,2017-12-13 15:16:07.975,1,16.352716,48.215687,223.163727,0.893687,221.838181,16.000000
1247,2017-12-13 15:16:06.999,2017-12-13 15:16:07.976,1,16.352716,48.215687,223.163727,0.893687,221.838181,16.000000
1248,2017-12-13 15:16:07.999,2017-12-13 15:16:09.015,1,16.352708,48.215680,223.241791,1.007915,213.887146,24.000000
1249,2017-12-13 15:16:07.999,2017-12-13 15:16:09.016,1,16.352708,48.215680,223.241791,1.007915,213.887146,24.000000
1250,2017-12-13 15:16:08.999,2017-12-13 15:16:10.051,1,16.352689,48.215653,223.233612,1.049214,205.248703,12.000000
1251,2017-12-13 15:16:08.999,2017-12-13 15:16:10.052,1,16.352689,48.215653,223.233612,1.049214,205.248703,12.000000
1252,2017-12-13 15:16:09.999,2017-12-13 15:16:11.034,1,16.352689,48.215653,223.248825,1.039616,205.248703,12.000000
1253,2017-12-13 15:16:09.999,2017-12-13 15:16:11.036,1,16.352689,48.215653,223.248825,1.039616,205.248703,12.000000
1254,2017-12-13 15:16:10.999,2017-12-13 15:16:11.975,1,16.352680,48.215639,223.282944,1.063178,202.523773,24.000000
1255,2017-12-13 15:16:10.999,2017-12-13 15:16:11.976,1,16.352680,48.215639,223.282944,1.063178,202.523773,24.000000
1256,2017-12-13 15:16:11.999,2017-12-13 15:16:13.023,1,16.352678,48.215631,223.373657,1.050253,202.523773,12.000000
1257,2017-12-13 15:16:11.999,2017-12-13 15:16:13.025,1,16.352678,48.215631,223.373657,1.050253,202.523773,12.000000
1258,2017-12-13 15:16:12.999,2017-12-13 15:16:14.177,1,16.352678,48.215631,223.363464,1.019313,202.523773,12.000000
1259,2017-12-13 15:16:12.999,2017-12-13 15:16:14.179,1,16.352678,48.215631,223.363464,1.019313,202.523773,12.000000
1260,2017-12-13 15:16:06.595,2017-12-13 15:16:14.216,0,16.352580,48.215716,0.000000,0.000000,0.000000,20.259001
1261,2017-12-13 15:16:06.595,2017-12-13 15:16:14.219,0,16.352580,48.215716,0.000000,0.000000,0.000000,20.259001
1262,2017-12-13 15:16:13.999,2017-12-13 15:16:14.982,1,16.352685,48.215619,223.368362,1.005124,157.054352,24.000000
1263,2017-12-13 15:16:13.999,2017-12-13 15:16:14.984,1,16.352685,48.215619,223.368362,1.005124,157.054352,24.000000
1264,2017-12-13 15:16:14.999,2017-12-13 15:16:16.043,1,16.352687,48.215607,223.364334,0.990389,181.472519,24.000000
1265,2017-12-13 15:16:14.999,2017-12-13 15:16:16.046,1,16.352687,48.215607,223.364334,0.990389,181.472519,24.000000
1266,2017-12-13 15:16:15.999,2017-12-13 15:16:16.972,1,16.352662,48.215570,223.376724,1.000618,209.474808,12.000000
1267,2017-12-13 15:16:15.999,2017-12-13 15:16:16.973,1,16.352662,48.215570,223.376724,1.000618,209.474808,12.000000